# Generated by Django 3.2.9 on 2021-12-04 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schoolUsers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_code', models.IntegerField()),
                ('fName', models.CharField(max_length=50)),
                ('sName', models.CharField(max_length=50)),
                ('fatherName', models.CharField(max_length=50)),
                ('motherName', models.CharField(max_length=50)),
                ('fee', models.IntegerField()),
                ('DOB', models.DateField()),
                ('student_present_class', models.CharField(choices=[('Nusery', 'nry'), ('LKG', 'lkg'), ('UKG', 'ukg'), ('1st', '1'), ('2nd', '2'), ('3rd', '3'), ('4th', '4'), ('5th', '5'), ('6th', '6'), ('7th', '7'), ('8th', '8'), ('9th', '9'), ('10th', '10'), ('11th', '11'), ('12th', '12')], default='Nusery', max_length=10)),
                ('address', models.CharField(max_length=50)),
                ('phoneNumber', models.IntegerField()),
                ('adhaar', models.IntegerField(default=12345)),
                ('religion', models.CharField(choices=[('MUSLIM', 'MUSLIM'), ('HINDU', 'HINDU'), ('CHRISTIAN', 'CHRISTIAN'), ('ATHEIST', 'ATHEIST'), ('SIKH', 'SIKH')], max_length=10)),
                ('caste', models.CharField(max_length=10)),
                ('category', models.CharField(choices=[('SC', 'SC'), ('OBC', 'OBC'), ('ST', 'ST'), ('GENERAL', 'GENERAL')], max_length=10)),
                ('last_year_percentage', models.CharField(max_length=3)),
                ('rte_student', models.BooleanField()),
                ('relatives_in_school', models.CharField(max_length=50)),
                ('insitution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolUsers.userregistion')),
            ],
        ),
    ]
