# Generated by Django 3.2.5 on 2021-12-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insitution', models.CharField(max_length=50)),
                ('student_code', models.IntegerField()),
                ('fName', models.CharField(max_length=50)),
                ('sName', models.CharField(max_length=50)),
                ('fatherName', models.CharField(max_length=50)),
                ('motherName', models.CharField(max_length=50)),
                ('fee', models.IntegerField()),
                ('DOB', models.DateField()),
                ('student_present_class', models.CharField(choices=[('NUSERY', 'NUSERY'), ('LKG', 'LKG'), ('UKG', 'UKG'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default='Nusery', max_length=10)),
                ('address', models.CharField(max_length=50)),
                ('state', models.CharField(default='.', max_length=30)),
                ('city', models.CharField(default='.', max_length=50)),
                ('phoneNumber', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('adhaar', models.IntegerField(default=12345)),
                ('religion', models.CharField(choices=[('MUSLIM', 'MUSLIM'), ('HINDU', 'HINDU'), ('CHRISTIAN', 'CHRISTIAN'), ('ATHEIST', 'ATHEIST'), ('SIKH', 'SIKH')], max_length=10)),
                ('caste', models.CharField(max_length=10)),
                ('category', models.CharField(choices=[('SC', 'SC'), ('OBC', 'OBC'), ('ST', 'ST'), ('GENERAL', 'GENERAL')], max_length=10)),
                ('last_year_percentage', models.CharField(default=0, max_length=3)),
                ('rte_student', models.BooleanField()),
                ('relatives_in_school', models.CharField(max_length=50)),
                ('slugfield', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
    ]
