# Generated by Django 3.2.9 on 2021-12-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_code', models.IntegerField()),
                ('fName', models.CharField(max_length=50)),
                ('sName', models.CharField(max_length=50)),
                ('fatherName', models.CharField(max_length=50)),
                ('motherName', models.CharField(max_length=50)),
                ('fee', models.IntegerField()),
                ('DOB', models.DateField()),
                ('student_present_class', models.CharField(choices=[('nry', 'Nusery'), ('lkg', 'LKG'), ('ukg', 'UKG'), ('1', '1st'), ('2', '2nd'), ('3', '3rd'), ('4', '4th'), ('5', '5th'), ('6', '6th'), ('7', '7th'), ('8', '8th'), ('9', '9th'), ('10', '10th'), ('11', '11th'), ('12', '12th')], default='Nusery', max_length=5)),
                ('address', models.CharField(max_length=50)),
                ('phoneNumber', models.IntegerField()),
                ('religion', models.CharField(choices=[('mus', 'MUSLIM'), ('hd', 'HINDU'), ('ch', 'CHRISTIAN'), ('at', 'ATHEIST'), ('sk', 'SIKH')], max_length=10)),
                ('caste', models.CharField(max_length=10)),
                ('category', models.CharField(choices=[('SC', 'SC'), ('OBC', 'OBC'), ('ST', 'ST'), ('GENERAL', 'GENERAL')], max_length=10)),
                ('last_year_percentage', models.CharField(max_length=3)),
                ('rte_student', models.BooleanField()),
                ('relatives_in_school', models.CharField(max_length=50)),
            ],
        ),
    ]
