# Generated by Django 3.2.9 on 2021-12-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='last_year_percentage',
            field=models.CharField(default=0, max_length=3),
        ),
    ]
