# Generated by Django 3.2.9 on 2021-12-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='religion',
            field=models.CharField(choices=[('MUSLIM', 'MUSLIM'), ('HINDU', 'HINDU'), ('CHRISTIAN', 'CHRISTIAN'), ('ATHEIST', 'ATHEIST'), ('SIKH', 'SIKH')], max_length=10),
        ),
    ]
