# Generated by Django 3.2.9 on 2021-12-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_religion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_present_class',
            field=models.CharField(choices=[('Nusery', 'nry'), ('LKG', 'lkg'), ('UKG', 'ukg'), ('1st', '1'), ('2nd', '2'), ('3rd', '3'), ('4th', '4'), ('5th', '5'), ('6th', '6'), ('7th', '7'), ('8th', '8'), ('9th', '9'), ('10th', '10'), ('11th', '11'), ('12th', '12')], default='Nusery', max_length=10),
        ),
    ]
