# Generated by Django 3.2.5 on 2021-12-10 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='city',
            field=models.CharField(default='.', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='state',
            field=models.CharField(default='.', max_length=20),
        ),
    ]
