# Generated by Django 3.2.9 on 2021-12-11 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_student_slugfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='state',
            field=models.CharField(default='.', max_length=30),
        ),
    ]
